### Numpy : Numerical Python

#### 수치계산용 파이썬 라이브러리

In [3]:
import numpy as np

# 넘파이 배열(리스트) 생성하기
a = np.arange(10)
a

a2 = np.arange(3, 9)
a2

a3 = np.arange(3, 9, 2)
a3


array([3, 5, 7])

In [4]:
# 넘파이 배열(리스트) 생성하기
b = [1, 2, 3, 4]
arr = np.array(b)
arr

array([1, 2, 3, 4])

In [5]:
import numpy as np

c = ['봄', '여름', '가을', '겨울']
arr2 = np.array(c)
arr2
print(arr2)

['봄' '여름' '가을' '겨울']


In [45]:
import numpy as np

순위 = 1 + np.arange(10)   # 0 ~ 9 
팀 = np.array(['SSG', 'LG', '키움', 'KT', '기아', 'NC', '삼성', '롯데', '두산', '한화'])
승 = np.array([88, 87, 80, 80, 70, 67, 66, 64, 60, 46])
패 = np.array([52, 55, 62, 62, 73, 74, 76, 76, 82, 96])
무 = np.array([4, 2, 2, 2, 1, 3, 2, 4, 2, 2])
승률 = np.array([0.629, 0.613, 0.563, 0.563, 0.490, 0.475, 0.465, 0.457, 0.423, 0.324])
# print(팀)
# print(승)

with open("datas/2022kbo.txt", 'w') as f:
    f.write("============ 2022 한국 프로야구 성적표 ============\n")
    head = "순위\t팀\t승\t패\t무\t승률"
    f.write(head)
    f.write('\n')
    for i in range(len(팀)): # 10번 반복
        txt = f'{순위[i]}\t{팀[i]}\t{승[i]}\t{패[i]}\t{무[i]}\t{승률[i]}\n'
        f.write(txt)

In [43]:
with open("datas/2022kbo.txt", 'r') as f:
    data = f.read()
    print(data)

### 넘파이의 N차원 배열
#### 1차원 배열은 벡터(vector)라 함
#### 2차원 배열은 행렬(matrix) - 수, 또는 문자를 괄호안에 직사각형 형태로 배열
#### 3차원 배열은 텐서(tensor)라 함

In [21]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 0], [0, 6]])
#print(A)
#print(A.shape)   #(2, 2) -> 2행 2열
#print(B)
#print(B.shape)

#인덱싱
print(A[0])
print(A[0][1])
print(A[1][1])

# 전체 조회
for row in B:
    print(row)

# 연산
print(A+B)
print(A-B)
print(A*B)
#print(A/B)

[1 2]
2
4
[3 0]
[0 6]
[[ 4  2]
 [ 3 10]]
[[-2  2]
 [ 3 -2]]
[[ 3  0]
 [ 0 24]]
